{{ if .Values.auth.serviceAccount.createBothSecrets }}
kind: Secret
apiVersion: v1
metadata:
  name: sa-json
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
type: Opaque
data:
  SA_CREDENTIALS: {{ .Values.auth.serviceAccount.serviceAccountJsonB64 | required "if auth.serviceAccount.createBothSecrets is enabled auth.serviceAccount.serviceAccountJsonB64 must be provided" }}
  service-account.json: {{ .Values.auth.serviceAccount.serviceAccountJsonB64 | required "if auth.serviceAccount.createBothSecrets is enabled auth.serviceAccount.serviceAccountJsonB64 must be provided" }}
  sa.json: {{ .Values.auth.serviceAccount.serviceAccountJsonB64 | required "if auth.serviceAccount.createBothSecrets is enabled auth.serviceAccount.serviceAccountJsonB64 must be provided" }}
---

kind: Secret
apiVersion: v1
metadata:
  name: eu.gcr.io
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "docver.dockerconfig" .Values.auth.serviceAccount.serviceAccountJsonB64 | b64enc }}

{{ end }}