kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.auth.dbCreds.secretName }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
type: Opaque
stringData:
  password: x9xv1mw0td
  EMBEDDING_STORE_PGVECTOR_PASSWORD: x9xv1mw0td
  postgres-password: l3CDRjHVmxXqg3Hj
  
  # This value must be fixed for now, do not change if creating a new secret
  EMBEDDING_STORE_PGVECTOR_USERNAME: embedding-store-sa
