version: '3'

services:
  doc-ver-runner:
    image: europe-docker.pkg.dev/microblink-identity/docver/runner:3.0.2-38b5f13 # todo: prod image
    healthcheck:
      test: ["CMD", "curl", "-f", "doc-ver-runner:8080/health/ready" ]
      interval: 15s
      timeout: 10s
      retries: 5
    environment:
      Executor__ApplicationId: ${APPLICATION_ID}
      Executor__LicenseKey: ${LICENSE_KEY}
      Executor__GeneralAnomalyServerUrl: "visual-anomaly:8080"
      Executor__ModelServingUrl: "model-proxy:8005"
      Executor__ModelServingSsl: false
    deploy:
      resources:
        limits:
          cpus: ${LIMITS_CPUS}
          memory: ${LIMITS_MEM}
        reservations:
          cpus: ${RESERVATIONS_CPUS}
          memory: ${RESERVATIONS_MEM}
    networks:
      - doc-ver-network

