
models:
    visual-anomaly:
        backendInferenceEngine: triton
        models:
            - id: 6478fcb410dcce6d3b037199
              modelSgn:
                inputs:
                    - typeId: Image
                      params:
                        decodeJpeg:
                            channelFirstRaster: true
                            channelOrder: RGB
                            resize:
                                height: 224
                                width: 224
                        imageInputKey: input
                outputs:
                    - typeId: GridEmbedding
                      params:
                        cols: 14
                        keyName: output
                        numChannels: 768
                        rows: 14
              backendInferenceEngine: triton
    photo-fraud-classifier:
        backendInferenceEngine: tfServing
        models:
            - id: 6684168e04248f708c1e0c93
              modelSgn:
                inputs:
                    - typeId: Image
                      params:
                        imageInputKey: image_input
                outputs:
                    - typeId: MaxClassification
                      params:
                        classNameOutput: label
                        scoreOutput: probability
              backendInferenceEngine: tfServing
    photocopy-classifier-contextual-unified:
        backendInferenceEngine: tfServing
        models:
            - id: 667a8f0b76c3ea3a32fcd565
              modelSgn:
                inputs:
                    - typeId: Image
                      params:
                        imageInputKey: image_input
                outputs:
                    - typeId: MaxClassification
                      params:
                        classNameOutput: label
                        scoreOutput: probability
              backendInferenceEngine: tfServing


