
models:
    visual-anomaly:
        backendInferenceEngine: triton
        models:
            - id: 6478fcb410dcce6d3b037199
              modelSgn:
                inputs:
                    - typeId: Image
                      params:
                        decodeJpeg:
                            channelFirstRaster: true
                            channelOrder: RGB
                            resize:
                                height: 224
                                width: 224
                        imageInputKey: input
                outputs:
                    - typeId: GridEmbedding
                      params:
                        cols: 14
                        keyName: output
                        numChannels: 768
                        rows: 14
              backendInferenceEngine: triton
    photo-fraud-classifier:
        backendInferenceEngine: tfServing
        models:
            - id: 6647158183f1d72d549f88e4
              modelSgn:
                inputs:
                    - typeId: Image
                      params:
                        imageInputKey: image_input
                outputs:
                    - typeId: MaxClassification
                      params:
                        classNameOutput: label
                        scoreOutput: probability
              backendInferenceEngine: tfServing
    photocopy-classifier-contextual-unified:
        backendInferenceEngine: tfServing
        models:
            - id: 6647d3aa83f1d72d549f88e8
              modelSgn:
                inputs:
                    - typeId: Image
                      params:
                        imageInputKey: image_input
                outputs:
                    - typeId: MaxClassification
                      params:
                        classNameOutput: label
                        scoreOutput: probability
              backendInferenceEngine: tfServing
            - id: 664f60da83f1d72d549f88f3
              modelSgn:
                inputs:
                    - typeId: Image
                      params:
                        imageInputKey: image_input
                outputs:
                    - typeId: MaxClassification
                      params:
                        classNameOutput: label
                        scoreOutput: probability
              backendInferenceEngine: tfServing
    photocopy-classifier-per-pixel-unified:
        backendInferenceEngine: tfServing
        models:
            - id: 6647d38e83f1d72d549f88e7
              modelSgn:
                inputs:
                    - typeId: Image
                      params:
                        imageInputKey: image_input
                outputs:
                    - typeId: MaxClassification
                      params:
                        classNameOutput: label
                        scoreOutput: probability
              backendInferenceEngine: tfServing
            - id: 664f60f083f1d72d549f88f4
              modelSgn:
                inputs:
                    - typeId: Image
                      params:
                        imageInputKey: image_input
                outputs:
                    - typeId: MaxClassification
                      params:
                        classNameOutput: label
                        scoreOutput: probability
              backendInferenceEngine: tfServing

