
models:
    visual-anomaly:
        backendInferenceEngine: triton
        models:
            - id: 6478fcb410dcce6d3b037199
              modelSgn:
                inputs:
                    - typeId: Image
                      params:
                        decodeJpeg:
                            channelFirstRaster: true
                            channelOrder: RGB
                            resize:
                                height: 224
                                width: 224
                        imageInputKey: input
                outputs:
                    - typeId: GridEmbedding
                      params:
                        cols: 14
                        keyName: output
                        numChannels: 768
                        rows: 14
              backendInferenceEngine: triton

