version: '3'

services:
  retrieval-intermediary:
    deploy:
      resources:
        limits:
          cpus: ${LIMITS_CPUS}
          memory: ${LIMITS_MEM}
        reservations:
          cpus: ${RESERVATIONS_CPUS}
          memory: ${RESERVATIONS_MEM}
    depends_on:
      model_proxy:
        condition: service_healthy
      embedding-store-server:
        condition: service_healthy
      seeder:
        condition: service_completed_successfully
    image: us-central1-docker.pkg.dev/document-verification-public/docver-gcm/anomaly-detection-intermediary/onprem:v0.10.8
    healthcheck:
      test: ["CMD", "grpc_health_probe", "-addr", "retrieval-intermediary:8005"]
      interval: 15s
      timeout: 10s
      retries: 5
    command: 
      - "/usr/bin/intermediary"
      - "server"
      - --model-id
      - "6478fcb410dcce6d3b037199"
      - --model-name
      - "visual-anomaly"
      - --model-proxy-addr
      - model_proxy:8005  
      - --embedding-store-addr
      - embedding-store-server:8005 
      - --embedding-store-secure
      - "false"
      - --collection-name
      - ${COLLECTION_NAME}
      - --parallel-queries
      - "${PARALLEL_QUERIES}"
    networks:
      - visual-anomaly-network
