version: '3'

services:
  model-proxy:
    depends_on:
      visual-anomaly-nginx:
        condition: service_healthy
    image: us-central1-docker.pkg.dev/document-verification-public/docver-gcm/mlp-model-proxy/onprem:v0.19.2
    healthcheck:
      test: ["CMD", "grpc_health_probe", "-addr", "model-proxy:8005"]
      interval: 15s
      timeout: 10s
      retries: 5
    networks:
      - doc-ver-network
    volumes:
      - ./proxy/bundle-signature.yaml:/etc/bundle-signature.yaml
    command:
      - mproxy
      - server
      - --tf-serving-connection-string
      - visual-anomaly-nginx:80
      - -c
      - /etc/bundle-signature.yaml

  visual-anomaly-nginx:
    depends_on:
      s6478fcb410dcce6d3b037199s:
        condition: service_healthy
      s66a00cd7fb85edd8517b6af3s:
        condition: service_healthy
      s66a0a678fb85edd8517b6af5s:
        condition: service_healthy
    image: fabiocicerchia/nginx-lua:1.25.2-alpine3.18.3
    healthcheck:
      test: ["CMD", "curl", "-f", "visual-anomaly-nginx:80/health"]
      interval: 15s
      timeout: 10s
      retries: 5
    networks:
      - doc-ver-network
    volumes:
      - ${REL_DIR}/conf/bundle/nginx.conf:/etc/nginx/nginx.conf

  s6478fcb410dcce6d3b037199s:
    depends_on:
      model_download:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "grpc_health_probe", "-addr", "s6478fcb410dcce6d3b037199s:8001"]
      interval: 15s
      timeout: 10s
      retries: 5
    image: us-central1-docker.pkg.dev/document-verification-public/docver-gcm/tritonserver-cpu-onnxruntime/onprem:23.06
    networks:
      - doc-ver-network
    volumes:
      - ./model-serving/model-download/models/6478fcb410dcce6d3b037199:/models/6478fcb410dcce6d3b037199
    command:
      - tritonserver
      - --model-repository=/models
    deploy:
      resources:
        limits:
          cpus:  ${SERVING_6478fcb410dcce6d3b037199_CPU_LIMIT}
          memory: ${SERVING_6478fcb410dcce6d3b037199_MEM_LIMIT}
        reservations:
          cpus: ${SERVING_6478fcb410dcce6d3b037199_CPU_RESERVATION}
          memory: ${SERVING_6478fcb410dcce6d3b037199_MEM_RESERVATION}


  s66a00cd7fb85edd8517b6af3s:
    depends_on:
      model_download:
        condition: service_completed_successfully
    image: us-central1-docker.pkg.dev/document-verification-public/docver-gcm/tf-serving-kira-native-cpu/onprem:v2.13.0
    networks:
      - doc-ver-network
    volumes:
      - ./model-serving/model-download/models/66a00cd7fb85edd8517b6af3:/models/66a00cd7fb85edd8517b6af3
    command:
      - --enable_model_warmup
      - --model_name=66a00cd7fb85edd8517b6af3
      - --model_base_path=/models/66a00cd7fb85edd8517b6af3
    healthcheck:
      test: ["CMD", "tfs_model_status_probe", "-addr", "s66a00cd7fb85edd8517b6af3s:8500", "-model-name", "66a00cd7fb85edd8517b6af3", "-model-version", "1", "|", "grep", "AVAILABLE"]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: ${SERVING_66a00cd7fb85edd8517b6af3_CPU_LIMIT}
          memory: ${SERVING_66a00cd7fb85edd8517b6af3_MEM_LIMIT}
        reservations:
          cpus: ${SERVING_66a00cd7fb85edd8517b6af3_CPU_RESERVATION}
          memory: ${SERVING_66a00cd7fb85edd8517b6af3_MEM_RESERVATION}
  s66a0a678fb85edd8517b6af5s:
    depends_on:
      model_download:
        condition: service_completed_successfully
    image: us-central1-docker.pkg.dev/document-verification-public/docver-gcm/tf-serving-kira-native-cpu/onprem:v2.13.0
    networks:
      - doc-ver-network
    volumes:
      - ./model-serving/model-download/models/66a0a678fb85edd8517b6af5:/models/66a0a678fb85edd8517b6af5
    command:
      - --enable_model_warmup
      - --model_name=66a0a678fb85edd8517b6af5
      - --model_base_path=/models/66a0a678fb85edd8517b6af5
    healthcheck:
      test: ["CMD", "tfs_model_status_probe", "-addr", "s66a0a678fb85edd8517b6af5s:8500", "-model-name", "66a0a678fb85edd8517b6af5", "-model-version", "1", "|", "grep", "AVAILABLE"]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: ${SERVING_66a0a678fb85edd8517b6af5_CPU_LIMIT}
          memory: ${SERVING_66a0a678fb85edd8517b6af5_MEM_LIMIT}
        reservations:
          cpus: ${SERVING_66a0a678fb85edd8517b6af5_CPU_RESERVATION}
          memory: ${SERVING_66a0a678fb85edd8517b6af5_MEM_RESERVATION}


  model_download:
    image: rclone/rclone:1
    networks:
      - doc-ver-network
    entrypoint: sh
    volumes:
      - ./model-serving/model-download/rclone.conf:/config/rclone/rclone.conf
      - ./model-serving/model-download/models:/models
      - ./model-serving/model-download/model-download.sh:/data/model-download.sh
    command: 
      - ./model-download.sh

networks:
  doc-ver-network:
