version: '3'

services:
  model-proxy:
    depends_on:
      visual-anomaly-nginx:
        condition: service_healthy
    image: us-central1-docker.pkg.dev/document-verification-public/docver-gcm/mlp-model-proxy/onprem:v0.19.2
    healthcheck:
      test: ["CMD", "grpc_health_probe", "-addr", "model-proxy:8005"]
      interval: 15s
      timeout: 10s
      retries: 5
    networks:
      - doc-ver-network
    volumes:
      - ./proxy/bundle-signature.yaml:/etc/bundle-signature.yaml
    command:
      - mproxy
      - server
      - --tf-serving-connection-string
      - visual-anomaly-nginx:80
      - -c
      - /etc/bundle-signature.yaml
    ports:
      - 62010:8005 # todo: remove this port - used for debugging proxy communication

  visual-anomaly-nginx:
    depends_on:
      s6478fcb410dcce6d3b037199s:
        condition: service_healthy
      s6684168e04248f708c1e0c93s:
        condition: service_healthy
      s667a8f0b76c3ea3a32fcd565s:
        condition: service_healthy
    image: fabiocicerchia/nginx-lua:1.25.2-alpine3.18.3
    healthcheck:
      test: ["CMD", "curl", "-f", "visual-anomaly-nginx:80/health"]
      interval: 15s
      timeout: 10s
      retries: 5
    networks:
      - doc-ver-network
    volumes:
      - ${REL_DIR}/conf/bundle/nginx.conf:/etc/nginx/nginx.conf

  s6478fcb410dcce6d3b037199s:
    depends_on:
      model_download:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "grpc_health_probe", "-addr", "s6478fcb410dcce6d3b037199s:8001"]
      interval: 15s
      timeout: 10s
      retries: 5
    image: us-central1-docker.pkg.dev/document-verification-public/docver-gcm/tritonserver-cpu-onnxruntime/onprem:23.06
    networks:
      - doc-ver-network
    volumes:
      - ./model-serving/model-download/models/6478fcb410dcce6d3b037199:/models/6478fcb410dcce6d3b037199
    command:
      - tritonserver
      - --model-repository=/models
    deploy:
      resources:
        limits:
          cpus:  ${SERVING_6478fcb410dcce6d3b037199_CPU_LIMIT}
          memory: ${SERVING_6478fcb410dcce6d3b037199_MEM_LIMIT}
        reservations:
          cpus: ${SERVING_6478fcb410dcce6d3b037199_CPU_RESERVATION}
          memory: ${SERVING_6478fcb410dcce6d3b037199_MEM_RESERVATION}


  s6684168e04248f708c1e0c93s:
    depends_on:
      model_download:
        condition: service_completed_successfully
    image: eu.gcr.io/driven-saga-88012/tf-serving-kira-native-cpu:v2.13.0-broadwell
    networks:
      - doc-ver-network
    volumes:
      - ./model-serving/model-download/models/6684168e04248f708c1e0c93:/models/6684168e04248f708c1e0c93
    command:
      - --enable_model_warmup
      - --model_name=6684168e04248f708c1e0c93
      - --model_base_path=/models/6684168e04248f708c1e0c93
    healthcheck:
      test: ["CMD", "tfs_model_status_probe", "-addr", "s6684168e04248f708c1e0c93s:8500", "-model-name", "6684168e04248f708c1e0c93", "-model-version", "1", "|", "grep", "AVAILABLE"]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: ${SERVING_6684168e04248f708c1e0c93_CPU_LIMIT}
          memory: ${SERVING_6684168e04248f708c1e0c93_MEM_LIMIT}
        reservations:
          cpus: ${SERVING_6684168e04248f708c1e0c93_CPU_RESERVATION}
          memory: ${SERVING_6684168e04248f708c1e0c93_MEM_RESERVATION}
  s667a8f0b76c3ea3a32fcd565s:
    depends_on:
      model_download:
        condition: service_completed_successfully
    image: eu.gcr.io/driven-saga-88012/tf-serving-kira-native-cpu:v2.13.0-broadwell
    networks:
      - doc-ver-network
    volumes:
      - ./model-serving/model-download/models/667a8f0b76c3ea3a32fcd565:/models/667a8f0b76c3ea3a32fcd565
    command:
      - --enable_model_warmup
      - --model_name=667a8f0b76c3ea3a32fcd565
      - --model_base_path=/models/667a8f0b76c3ea3a32fcd565
    healthcheck:
      test: ["CMD", "tfs_model_status_probe", "-addr", "s667a8f0b76c3ea3a32fcd565s:8500", "-model-name", "667a8f0b76c3ea3a32fcd565", "-model-version", "1", "|", "grep", "AVAILABLE"]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: ${SERVING_667a8f0b76c3ea3a32fcd565_CPU_LIMIT}
          memory: ${SERVING_667a8f0b76c3ea3a32fcd565_MEM_LIMIT}
        reservations:
          cpus: ${SERVING_667a8f0b76c3ea3a32fcd565_CPU_RESERVATION}
          memory: ${SERVING_667a8f0b76c3ea3a32fcd565_MEM_RESERVATION}


  model_download:
    image: rclone/rclone:1
    networks:
      - doc-ver-network
    entrypoint: sh
    volumes:
      - ./model-serving/model-download/rclone.conf:/config/rclone/rclone.conf
      - ./model-serving/model-download/models:/models
      - ./model-serving/model-download/model-download.sh:/data/model-download.sh
    command: 
      - ./model-download.sh

networks:
  doc-ver-network:
